groups:
  - name: HOST
    rules:
      - alert: High CPU Load
        expr: node_load1 > 1.5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Server under high load"
          description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

      - alert: High Memory Load
        expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Server memory is almost full"
          description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

      - alert: High Storage Load
        expr: (node_filesystem_size_bytes{fstype=~"ext.*|xfs"} - node_filesystem_free_bytes{fstype=~"ext.*|xfs"}) / node_filesystem_size_bytes{fstype=~"ext.*|xfs"}  * 100 > 85
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Server storage is almost full"
          description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - name: CONTAINERS
    rules:
      - alert: Too Many Restarts
        expr: count by (name) (count_over_time(container_last_seen{name!="", container_label_restartcount!="", container_label_org_label_schema_group="monitoring"}[15m])) - 1 >= 5
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Container Stuck in Restart Phase: {{ $labels.name }}"
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
